### ISSUE TITLE
No write access to repo

### ISSUE THREAD

**Issue by plinnegan** [pepfar-datim/dashboard-information-widget#1]
@benguaraldi I could clone the repo, but it does not seem like I am allowed to push to it at the moment. Could you please give me write access to dashboard-information-widget when you get in today?

```
plinnegan@Peters-MacBook-Pro:~/g/4/dashboard-information-widget|main✓
➤ git push
ERROR: Permission to pepfar-datim/dashboard-information-widget.git denied to plinnegan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by benguaraldi** [comment]
@Lownin Could you give the DATIM Dev Team write access to this repo?

**Comment by Lownin** [comment]
Done!

**Comment by benguaraldi** [comment]
@plinnegan Please verify and close.  Thanks!

**Comment by plinnegan** [comment]
Access granted, thanks both!
