### ISSUE TITLE
Non-Superuser Permissions Issue

### ISSUE THREAD

**Issue by s-paton** [pepfar-datim/dashboard-information-widget#12]
**Observed behaviour:** Non-superusers in DHIS2 are unable to edit information app dashboards objects despite having permission to the Information app and the Datastore app, as well as the 'Only open to superusers' Datastore configuration remaining unticked. On clicking save, the messaging "Error: Cannot save" is displayed in the DHIS2 UI and 403 error in the API response: "Access denied for key 'qrhEYnkyKdp' in namespace 'dashboard-information'". Non-superusers in this instance are those that don't have the 'All (Full authority)' permission. This has been observed on versions 1.1.4 of the app on DHIS2 2.38 and 2.40.

<img width="381" alt="image" src="https://github.com/pepfar-datim/dashboard-information-widget/assets/171344974/e7233dbb-d234-47be-b564-09d20aa09d1b">
<img width="714" alt="image" src="https://github.com/pepfar-datim/dashboard-information-widget/assets/171344974/f34bbb5d-6403-4637-b180-efccc12e69bc">

**Comment by benguaraldi** [comment]
@jakub-bao was in touch with @s-paton and recommended the following:
> It seems like the user who's trying to edit the dashboard content via the Information app doesn't have edit permissions for 'dashboard-information' in DHIS2 data store.
>
> That's where we store the edited content of the widget.
>
> If you want, you can try to adjust the permissions of the data store namespace to allow these types of users to edit the content.

@s-paton tried that and it didn't work.

@s-paton, perhaps the next step is to remove the app and the `dashboard-information` namespace and then reinstall both?  If you have a dev or test server, you could try it on that server to see if it helps the situation.

**Comment by benguaraldi** [comment]
We haven't heard from @s-paton in a while, so I'm closing this.

**Comment by s-paton** [comment]
Sorry @benguaraldi for the delay - didn't have time to test again until now. Reinstalling the app made no difference, but recreating the namespace worked! Thanks for the help 👍
