### ISSUE TITLE
Create Jest-based test suite

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/dashboard-information-widget#2]
Per @jakub-bao in an old repo:
> @plinnegan noticed we don't have a test coverage for Dashboard Info app.
> It would be great to put together one.
> 
> I'd suggest a bunch of tests written using Jest / react testing library (same as e.g. ERB Processor)
> 
> We should probably test these areas:
> - app creates datastore entry on first boot
> - app fetches data from datastore
> - app renders html correctly (font, img, video, link)
> - app removes forbidden html (javascript tag, javascript inside onclick, etc.)
> - app save data in datastore

Per me:
> Also, we should test that the app sets the permissions correctly for the datastore items.

**Comment by plinnegan** [comment]
@jakub-bao I can't find the ERB processor on github, could you please link it to me? Testing is slightly more complicated than usual as the app is typically run in an iframe on an instance on DHIS2 and most of the tests requested relate to testing interactions between the app and DHIS2, so I am keen to see if I can learn some things from the ERB app if it is similar.

**Comment by benguaraldi** [comment]
@plinnegan Here it is: https://github.com/pepfar-datim/ERB-Processor

**Comment by benguaraldi** [comment]
This ticket is now being tracked at https://jira.pepfar.net/browse/DAT-93. Closing.
